name: Model Retraining on Push

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  retrain:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [rf]  # add logreg to compare both

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Make timestamp (output)
        id: ts
        run: echo "value=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: Train
        run: |
          python ./src/train_model.py --timestamp "${{ steps.ts.outputs.value }}" --model "${{ matrix.model }}"

      - name: Evaluate
        run: |
          python ./src/evaluate_model.py --timestamp "${{ steps.ts.outputs.value }}" --model "${{ matrix.model }}"

      - name: Upload artifacts (model & metrics)
        uses: actions/upload-artifact@v4
        with:
          name: model_${{ steps.ts.outputs.value }}_${{ matrix.model }}
          path: |
            models/model_${{ steps.ts.outputs.value }}_${{ matrix.model }}.joblib
            metrics/${{ steps.ts.outputs.value }}_*.json

      - name: Commit model & metrics to repo
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add models/ metrics/
          git commit -m "ci: add model & metrics (${{ steps.ts.outputs.value }} ${{ matrix.model }})" || echo "nothing to commit"
          git push