name: Model Calibration on Push

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  calibrate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [rf]
        method: [isotonic, sigmoid]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Find latest timestamp for this model
        id: latest
        shell: bash
        run: |
          ls -1 models/model_*_${{ matrix.model }}.joblib | sed -E 's#.*/model_([0-9]{14})_.*#\1#' | sort | tail -n1 > latest_ts.txt
          echo "value=$(cat latest_ts.txt)" >> "$GITHUB_OUTPUT"

      - name: Calibrate
        run: |
          python ./src/calibrate_model.py \
            --timestamp "${{ steps.latest.outputs.value }}" \
            --model "${{ matrix.model }}" \
            --method "${{ matrix.method }}"

      - name: Upload calibrated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: calibrated_${{ steps.latest.outputs.value }}_${{ matrix.model }}_${{ matrix.method }}
          path: |
            models/model_${{ steps.latest.outputs.value }}_${{ matrix.model }}_cal_${{ matrix.method }}.joblib
            metrics/${{ steps.latest.outputs.value }}_calibration_${{ matrix.method }}.json

      - name: Commit calibrated model & metrics
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add models/ metrics/
          git commit -m "ci: add calibrated model & metrics (${{ steps.latest.outputs.value }} ${{ matrix.model }} ${{ matrix.method }})" || echo "nothing to commit"
          git push