# Dockerfile
FROM python:3.9-slim

# 1) create workdir
WORKDIR /app

# 2) copy requirements first (better layer caching)
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# 3) copy source
COPY src/ ./src/

# 4) default envs (can be overridden at docker run)
ENV MODEL_DIR=/app/models

# 5) default command: train
CMD ["python", "src/train.py"]